# Book settings
title: Brain Computation
author: Kenji Doya
logo: BC_logo.png

# Force re-execution of notebooks on each build.
#execute:
#  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: BrainComputation.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - BrainComputation.bib

# Information about where the book exists on the web
#repository:
#  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
#  path_to_book: docs  # Optional path to your book, relative to the repository root
#  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
#html:
#  use_issues_button: true
#  use_repository_button: true
